services:
  immich-consume:
    build: .
    restart: unless-stopped
    volumes:
      - ./consume:/consume
    environment:
      - IMMICH_SERVER=${IMMICH_SERVER}
      - IMMICH_API_KEY=${IMMICH_API_KEY}
      # Optionally set additional args for immich-go, e.g. --album
      - IMMICH_EXTRA_ARGS=${IMMICH_EXTRA_ARGS:-}
      - IMMICH_SILENT=${IMMICH_SILENT:-1}
      - FAILED_DIR_NAME=${FAILED_DIR_NAME:-failed_uploads}
